### PR TITLE
Fix issues with the introspect tool

### LINKED ISSUE #70: ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
Running mcp server with uplink providing schema to MCP, commandline being used to startup:

`
APOLLO_GRAPH_REF="########" APOLLO_KEY="##########" /Users/username/dev/apollo/apollo-mcp-server/target/debug/apollo-mcp-server --directory /Users/username/dev/apollo/apollo-mcp-server --uplink --sse-address 127.0.0.1 --sse-port 5000 --introspection
`

Results in output of:
```
2025-05-21T18:17:13.160487Z  INFO apollo_mcp_server: Apollo MCP Server v0.1.0 // (c) Apollo Graph, Inc. // Licensed as ELv2 (https://go.apollo.dev/elv2)
2025-05-21T18:17:17.831980Z  INFO apollo_mcp_server::server: Running with schema:
<SNIP>
I've redacted the schema here, but the correct schema is output here
<SNIP>
2025-05-21T18:16:30.602197Z  INFO apollo_mcp_registry::uplink::persisted_queries::manifest_poller: Loaded 0 persisted queries.
2025-05-21T18:16:30.602804Z  INFO apollo_mcp_registry::uplink::persisted_queries::manifest_poller: persisted query manifest successfully updated (0 operations total)
2025-05-21T18:16:30.603088Z  WARN apollo_mcp_server::operations: No operations found
2025-05-21T18:16:30.604327Z  INFO apollo_mcp_server::server: Starting MCP server in SSE mode port=5000 address=127.0.0.1
```

When attempting to introspect via tool getting the following output:

```
2025-05-21T18:04:17.927654Z  INFO rmcp::service: response message id=2 result=ListToolsResult(ListToolsResult { next_cursor: None, tools: [Tool { name: "execute", description: "Execute a GraphQL operation. Use the `introspect` tool to get information about the GraphQL schema. Always use the schema to create operations - do not try arbitrary operations. DO NOT try to execute introspection queries.", input_schema: {"$schema": String("http://json-schema.org/draft-07/schema#"), "title": String("Input"), "type": String("object"), "required": Array [String("query")], "properties": Object {"query": Object {"description": String("The GraphQL operation"), "type": String("string")}, "variables": Object {"description": String("The variable values"), "type": Array [String("string"), String("null")]}}} }, Tool { name: "introspect", description: "Get detailed information about types from the GraphQL schema. Use the type name `Query` to get root query fields.", input_schema: {"$schema": String("http://json-schema.org/draft-07/schema#"), "title": String("IntrospectInput"), "type": String("object"), "required": Array [String("type_name")], "properties": Object {"depth": Object {"description": String("How far to recurse the type hierarchy. Use 0 for no limit. Defaults to 1."), "default": Number(1), "type": String("integer"), "format": String("uint32"), "minimum": Number(0.0)}, "type_name": Object {"description": String("The name of the type to get information about."), "type": String("string")}}} }] })
2025-05-21T18:04:27.933141Z  INFO rmcp::service: received request id=3 request=CallToolRequest(Request { method: CallToolRequestMethod, params: CallToolRequestParam { name: "introspect", arguments: Some({"type_name": String("Query"), "depth": Number(1)}) } })
2025-05-21T18:04:27.974976Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975314Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975332Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975373Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975386Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975395Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975404Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975412Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975424Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975433Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975486Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975516Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975526Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975534Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975544Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975552Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975625Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975730Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975828Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975840Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975846Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975854Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975860Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975866Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975871Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975908Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975915Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.975925Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.976098Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.976110Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.976203Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.976279Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.976300Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.976345Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.976509Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.976518Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.976524Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-21T18:04:27.988693Z  INFO rmcp::service: response message id=3 result=CallToolResult(CallToolResult { content: [], is_error: None })```

### PR DESCRIPTION
**Pull request by DaleSeo**
fixes #70 

This PR addresses two issues with the `introspect` tool:

-  It resolves the error `argument type reason not found` that occurs when a schema contains directives.
-  It fixes the problem  where no content is returned when a schema includes the `Subscription` top-level type.

## Before

Shot 2025-05-23 at 15 06 46

```sh
2025-05-23T19:06:04.917064Z  INFO rmcp::service: received request id=2 request=CallToolRequest(Request { method: CallToolRequestMethod, params: CallToolRequestParam { name: "introspect", arguments: Some({"depth": Number(1), "type_name": String("Query")}) } })
2025-05-23T19:06:04.934714Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-23T19:06:04.934718Z ERROR apollo_mcp_server::schema_tree_shake: argument type reason not found
2025-05-23T19:06:04.940833Z  INFO rmcp::service: response message id=2 result=CallToolResult(CallToolResult { content: [], is_error: None })
```

## After

Shot 2025-05-23 at 15 12 18

```sh
2025-05-23T19:11:57.978978Z  INFO rmcp::service: received request id=1 request=ListToolsRequest(Request { method: ListToolsRequestMethod, params: Some(PaginatedRequestParamInner { cursor: None }) })
2025-05-23T19:11:57.979078Z  INFO rmcp::service: response message id=1 result=ListToolsResult(ListToolsResult { next_cursor: None, tools: [Tool { name: "execute", description: "Execute a GraphQL operation. Use the `introspect` tool to get information about the GraphQL schema. Always use the schema to create operations - do not try arbitrary operations. DO NOT try to execute introspection queries.", input_schema: {"$schema": String("http://json-schema.org/draft-07/schema#"), "title": String("Input"), "type": String("object"), "required": Array [String("query")], "properties": Object {"query": Object {"description": String("The GraphQL operation"), "type": String("string")}, "variables": Object {"description": String("The variable values"), "default": String(""), "type": String("string")}}} }, Tool { name: "introspect", description: "Get detailed information about types from the GraphQL schema. Use the type name `Query` to get root query fields.", input_schema: {"$schema": String("http://json-schema.org/draft-07/schema#"), "title": String("IntrospectInput"), "type": String("object"), "required": Array [String("type_name")], "properties": Object {"depth": Object {"description": String("How far to recurse the type hierarchy. Use 0 for no limit. Defaults to 1."), "default": Number(1), "type": String("integer"), "format": String("uint32"), "minimum": Number(0.0)}, "type_name": Object {"description": String("The name of the type to get information about."), "type": String("string")}}} }] })
2025-05-23T19:12:04.723734Z  INFO rmcp::service: received request id=2 request=CallToolRequest(Request { method: CallToolRequestMethod, params: CallToolRequestParam { name: "introspect", arguments: Some({"depth": Number(1), "type_name": String("Query")}) } })
2025-05-23T19:12:04.724632Z  INFO rmcp::service: response message id=2 result=CallToolResult(CallToolResult { content: [Annotated { raw: Text(RawTextContent { text: "type Query {\n  users: [User!]! @deprecated(reason: \"Use 'allUsers' instead for better performance\")\n  allUsers(limit: Int, offset: Int): UserConnection!\n  getUser(id: ID!): User @deprecated\n  user(id: ID!): User\n  posts: [Post!]!\n}\n" }), annotations: None }], is_error: None })
```

### CODE REVIEW

File: crates/apollo-mcp-server/src/introspection.rs [hunk 1]
```diff
@@ -117,7 +117,9 @@ impl Introspect {
                             })
                         && schema
                             .root_operation(OperationType::Subscription)
-                            .is_none_or(|root_name| extended_type.name() == root_name)
+                            .is_none_or(|root_name| {
+                                extended_type.name() != root_name || type_name == root_name.as_str()
+                            })
```
Comment (Jephuff) [inline crates/apollo-mcp-server/src/introspection.rs:122]: @pubmodmatt Do you remember why we added these?
I think these were probably added to match the `OperationType::Query` type, but `OperationType::Query` is the only one that always gets added because it's required to make a valid schema. 
I'm thinking we can actually delete lines 113 to 122

File: crates/apollo-mcp-server/src/schema_tree_shake.rs [hunk 2]
```diff
@@ -1125,4 +1126,24 @@ mod test {
...
         );
     }
+
+    #[test]
+    fn should_retain_directives() {
+        let source_text = r#"
+            type Query {
+                field1: String @deprecated(reason: "Use 'field2' instead")
+                field2: String
+            }
```
Comment (Jephuff) [inline crates/apollo-mcp-server/src/schema_tree_shake.rs:1136]: Could we add another test where the argument should be kept, so a custom directive with a custom type
Something like 
```suggestion
             scalar CustomScalar
             directive @CustomDirective(arg: CustomScalar) on FIELD_DEFINITION
             type Query {
                field1: String @CustomDirective(arg: "Use 'field2' instead")
                field2: String
            }
```

Comment (DaleSeo) [reply crates/apollo-mcp-server/src/schema_tree_shake.rs:1136]: Great suggestion, @Jephuff! I have added the test.

File: crates/apollo-mcp-server/src/introspection.rs (hunk 1 above)
Comment (pubmodmatt) [reply crates/apollo-mcp-server/src/introspection.rs:122]: I think you're right - the Query case is needed since the shaker always adds that, but the others can be removed. It's questionable to me whether the shaker should even include Query - we could just say that the returned schema isn't strictly valid.

Comment (Jephuff) [reply crates/apollo-mcp-server/src/introspection.rs:122]: I think we should 100% stop adding Query, I added when I was returning a Valid<Schema> and we already changed it to return the full result with the WithErrors<Schema> so I don't think we need to worry about it anymore. 

maybe lets merge this fix because it's pretty important and then as a follow up we can cleanup adding the Query type and remove all 3 conditions here?

Comment (pubmodmatt) [reply crates/apollo-mcp-server/src/introspection.rs:122]: sounds good!
